// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGvW_cGXWG0H2ZTg0JKaIXuva28hUSEZE',
    appId: '1:135334730332:web:72720c86e7563f4a042499',
    messagingSenderId: '135334730332',
    projectId: 'book-bazaar-5af69',
    authDomain: 'book-bazaar-5af69.firebaseapp.com',
    storageBucket: 'book-bazaar-5af69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj8U5zPFpSdPwyKfjTKoUNGCfxsy_KRr4',
    appId: '1:135334730332:android:7bf56b106c4a9bf1042499',
    messagingSenderId: '135334730332',
    projectId: 'book-bazaar-5af69',
    storageBucket: 'book-bazaar-5af69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2bOqpEimhbUuCVpc5FncxikubE24CZhc',
    appId: '1:135334730332:ios:e5880079c536e7eb042499',
    messagingSenderId: '135334730332',
    projectId: 'book-bazaar-5af69',
    storageBucket: 'book-bazaar-5af69.firebasestorage.app',
    iosBundleId: 'com.example.bookBazaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2bOqpEimhbUuCVpc5FncxikubE24CZhc',
    appId: '1:135334730332:ios:e5880079c536e7eb042499',
    messagingSenderId: '135334730332',
    projectId: 'book-bazaar-5af69',
    storageBucket: 'book-bazaar-5af69.firebasestorage.app',
    iosBundleId: 'com.example.bookBazaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGvW_cGXWG0H2ZTg0JKaIXuva28hUSEZE',
    appId: '1:135334730332:web:1d4316f8766e4252042499',
    messagingSenderId: '135334730332',
    projectId: 'book-bazaar-5af69',
    authDomain: 'book-bazaar-5af69.firebaseapp.com',
    storageBucket: 'book-bazaar-5af69.firebasestorage.app',
  );
}
